### ISSUE TITLE
Implement flow for CMIP6 transfers pipeline

### ISSUE THREAD

**Issue by kyleredilla** [ua-snap/prefect#15]
[transfers pipeline](https://github.com/ua-snap/cmip6-utils/tree/ce40d86ad6868a51c273a8631657b1ea2cfbe6b6/transfers)

**Comment by Joshdpaul** [comment]
Due to the interactive nature of the Globus transfer process (especially the authentication steps that redirect you to a browser for a login code), this may not be a good candidate for a Prefect flow.

**Comment by kyleredilla** [comment]
Agreed! I think there's gonna be more complexity here than it's worth. Let's close this one.
